# Generated by Django 3.0.6 on 2020-06-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200603_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='subtitle'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='subtitle', max_length=180),
        ),
    ]
