# Generated by Django 3.0.6 on 2020-06-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200603_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='book_writer',
        ),
        migrations.AlterField(
            model_name='post',
            name='book_url',
            field=models.URLField(blank=True),
        ),
    ]
