# Generated by Django 3.0.6 on 2020-06-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200610_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='post',
            name='tech',
            field=models.CharField(default='Technology', max_length=180),
        ),
    ]
