# Generated by Django 3.0.6 on 2020-06-11 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200610_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tech',
            field=models.CharField(default='Tech1', max_length=180),
        ),
    ]
