# Generated by Django 3.0.6 on 2020-06-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200611_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_url',
            new_name='code_link',
        ),
    ]
