# Generated by Django 3.0.7 on 2020-06-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200629_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tech',
            field=models.CharField(default='Tech-Used', max_length=180),
        ),
    ]
