# Generated by Django 3.0.7 on 2020-06-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200629_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='para_2',
            field=models.TextField(blank=True, default='content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='para_3',
            field=models.TextField(blank=True, default='content'),
        ),
    ]
