# Generated by Django 3.0.7 on 2020-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200629_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='para_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='para_3',
            field=models.TextField(blank=True),
        ),
    ]
