# Generated by Django 3.0.7 on 2020-07-20 11:42

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200629_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='para_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='para_3',
        ),
        migrations.AlterField(
            model_name='post',
            name='para_1',
            field=djrichtextfield.models.RichTextField(default='content'),
        ),
    ]
