# Generated by Django 3.0.7 on 2020-07-20 12:01

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200720_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
