# Generated by Django 3.0.7 on 2020-09-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200720_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tech',
            field=models.CharField(choices=[('Python', 'Python'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('Php', 'Php'), ('Html', 'Html'), ('Dsa', 'Dsa'), ('Css', 'Css'), ('Bootstrap', 'Bootstrap'), ('Node.js', 'Node.js'), ('Angular', 'Angular'), ('React', 'React'), ('Flutter', 'Flutter')], default='Tech-Used', max_length=180),
        ),
    ]
