# Generated by Django 2.0 on 2020-05-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='bio', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
